version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=change_me_in_prod
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
